# Generated by Django 2.0 on 2018-01-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewLink',
            new_name='NewsLink',
        ),
    ]
